name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Adjust this to match the branch you want to trigger the build.

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Determine and increment version
      id: versioning
      run: |
        if [ -f VERSION ]; then
          echo "VERSION file exists. Reading current version..."
          VERSION=$(cat VERSION)
        else
          echo "VERSION file does not exist. Setting initial version..."
          VERSION="0.0.0"
        fi
        echo $VERSION

        IFS='.' read -ra VERSION_PARTS <<< "$VERSION"
        PATCH=${VERSION_PARTS[2]}
        echo "patch $PATCH"
        PATCH = $PATCH++
        echo "new patch $PATCH"
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH"
        echo "New VERSION: $NEW_VERSION"
        echo "$NEW_VERSION" > VERSION
        echo "::set-output name=new_version::$NEW_VERSION"
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

    - name: Extract repository name
      id: repo_name
      run: |
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        echo "::set-output name=name::$REPO_NAME"

    - name: Build and push the Docker image version
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo_name.outputs.name }}:${{ steps.versioning.outputs.new_version }}

    - name: Build and push the Docker image latest
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.repo_name.outputs.name }}:latest


    - name: Update VERSION file (Optional)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Actions"
        git add VERSION
        git commit -m "Update version to ${{ steps.inc_patch.outputs.new_version }}"
        git push
